### ISSUE TITLE
dependencies libcoin

### ISSUE THREAD

**Issue by makleelux** [ElainaYao/TimeVaryingData_LTRCforests#2]
Hi,

I am interesting in trying out the package. Looking at the rich documentation I was especially interested in trying out the real data example and would have liked to try it out on my own data.
However I struggle setting up the workspace. To be precise, loading LTRCforests provokes the following error: 

> library(LTRCforests)
Error: package or namespace load failed for ‘LTRCforests’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘libcoin’

I tried to manually install libcoin but this ends in the following error:

* installing *source* package ‘libcoin’ ...
** package ‘libcoin’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/mvtnorm/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c libcoin-init.c -o libcoin-init.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/mvtnorm/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c libcoin.c -o libcoin.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o libcoin.so libcoin-init.o libcoin.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libcoin.so] Error 1
ERROR: compilation failed for package ‘libcoin’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/libcoin’
Warning in install.packages :
  installation of package ‘libcoin’ had non-zero exit status
ERROR: dependency ‘libcoin’ is not available for package ‘coin’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/coin’
Warning in install.packages :
  installation of package ‘coin’ had non-zero exit status

Could you tell me if you know a way how to nonetheless try out your interesting package?

Kind regards and many excuses if that request rather belongs to libcoin.

Best
maklee

**Comment by ElainaYao** [comment]
Hi there,

Thank you for your interest in our packages! I am also very sorry to hear that! Yes, since our package is built upon partykit package, which requires to load libcoin, I am afraid the package libcoin has to be installed in the first place. 

I am wondering if you download the package from the github but not directly from CRAN. If you download it from github, please delete it and try to install it from CRAN using the command install.packages("LTRCforests"). I would expect it would not less problematic if the package is installed from CRAN, since CRAN usually checks all these issues before it allows the publication. If you do not have certain packages, they should automatically download it for you.

I had some similar issues before, not from "libcoin" or "coin" but some other packages, saying the same thing as "installation of package ‘...’ had non-zero exit status". Usually it is because of the past failed attempt to install those packages which conflicts with the current attempt. Therefore, I would also suggest you to first locate your local folder where all the R packages are downloaded, and manually delete the folders named "libcoin" and "coin" if you see them. Then try to download LTRCforests on CRAN, by using install.packages("LTRCforests") (or install.packages("libcoin"); install.packages("coin")).

Hope that helps! Otherwise, I think you should contact the libcoin. Hopefully this will solve your issues! 

Best,
Weichi

**Comment by makleelux** [comment]
Thank you very much for your response. I indeed made a mistake having installed the binary version of libcoin which needs to be compiled.
Following your instruction (locating the packages, deleting, reinstalling from cran and choosing the right version of libcoin) worked out.
Many thanks! Very much looking forward to trying out your package!

Best,
make
